name: pre-commit

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  linting:
    name: run
    runs-on: ubuntu-latest
    steps:
      - name: Check out a copy of the repository
        uses: actions/checkout@v2

      - name: Install pre-commit
        shell: bash
        run: |
          sudo apt install python3 python3-pip
          python3 -m pip install pre-commit
          pre-commit install

      - name: Install dependencies of pre-commit hooks
        shell: bash
        run: |
          sudo apt install clang-format
          sudo apt install clang-tidy
          sudo apt install cppcheck

      - name: Run pre-commit on all files changed in this branch using project standard configuration
        shell: bash
        run: |
          echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
          echo "GITHUB_HEAD_REF = $GITHUB_HEAD_REF"
          git diff --name-only $GITHUB_BASE_REF...$GITHUB_HEAD_REF
          pre-commit run --from-ref $GITHUB_BASE_REF --to-ref $GITHUB_HEAD_REF
